name: Our Workflow
on: push
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - run: ls -al
      - uses: actions/checkout@v3
        with: # checkout에 입력 파라미터 주기
          path: our-source
      - run: ls -al
      - run: cat .github/workflows/checkout.yml
      
      
